enable_debug_for_admins:
  type: bool
  default: true
  description: "Check for Admins only debug info in console"
enable_debug_for_all:
  type: bool
  default: false
  description: "Check for All users debug info in console"
  